name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  buildImage:
    runs-on: ubuntu-latest

    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4

      - name: Docker Image bauen
        run: docker build -t github-actions-demo:latest .

      - name: Docker Images anzeigen
        run: docker images

      - name: Docker Container starten
        run: docker run --rm github-actions-demo:latest
